## Loading Data and basic look

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv("./WDI data/WDI_data.csv")

In [3]:
df.head(10)

,Country Name,Country Code,Series Name,Series Code,2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],...,2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023]
0,Afghanistan,AFG,GDP (current US$),NY.GDP.MKTP.CD,3521418059.92345,2813571753.87253,3825701438.99963,4520946818.54581,5224896718.67782,6203256538.70967,...,20497128555.6972,19134221644.7325,18116572395.0772,18753456497.8159,18053222687.4126,18799444490.1128,19955929052.1496,14259995441.0759,14497243872.1337,17233051620.1117
1,Afghanistan,AFG,GDP per capita (current US$),NY.GDP.PCAP.CD,174.930991430166,138.706821676113,178.954088379235,198.871115728727,221.763653873013,254.184249149336,...,625.054941813938,565.569730408751,522.082215583898,525.469770891619,491.337221382603,496.6025042585,510.787063366811,356.496214115892,357.261152798144,415.707417059086
2,Afghanistan,AFG,GDP growth (annual %),NY.GDP.MKTP.KD.ZG,..,-9.4319740700862,28.6000011706788,8.83227780288267,1.41411799339429,11.2297148272859,...,2.72454336219565,1.45131466066431,2.26031420279821,2.6470032027451,1.18922812944517,3.91160341625552,-2.35110067203466,-20.7388393676343,-6.24017199240269,2.71088679128353
3,Afghanistan,AFG,"Inflation, consumer prices (annual %)",FP.CPI.TOTL.ZG,..,..,..,..,..,12.6862687216715,...,4.67399603536305,-0.66170916471352,4.38389195513893,4.97595150553892,0.626149149168983,2.30237251516819,..,..,..,..
4,Afghanistan,AFG,"Unemployment, total (% of total labor force) (...",SL.UEM.TOTL.ZS,7.935,7.953,7.93,7.88,7.899,7.885,...,7.915,9.052,10.133,11.184,11.196,11.185,11.71,11.994,14.1,13.991
5,Afghanistan,AFG,Exports of goods and services (% of GDP),NE.EXP.GNFS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,10.4208171386207,14.342152797537,18.3800424016375,16.7751362822863
6,Afghanistan,AFG,Imports of goods and services (% of GDP),NE.IMP.GNFS.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,36.2890774127896,37.06956357719,54.5054272070161,50.498206993764
7,Afghanistan,AFG,"Foreign direct investment, net inflows (% of GDP)",BX.KLT.DINV.WD.GD.ZS,..,..,..,0.0221192604146061,-0.0133973940096779,0.0241808474410122,...,0.209664794672203,0.88400046336123,0.516606084523093,0.274796791572807,0.661572217787196,0.124495985291258,0.0649939571808755,0.215925454725649,..,..
8,Afghanistan,AFG,"Central government debt, total (% of GDP)",GC.DOD.TOTL.GD.ZS,..,..,..,..,..,..,...,..,..,..,..,..,..,..,..,..,..
9,Afghanistan,AFG,Tax revenue (% of GDP),GC.TAX.TOTL.GD.ZS,..,..,..,..,..,..,...,6.88210294277301,7.58538233129798,9.50265278288094,9.89845089688421,..,..,..,..,..,..

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125 entries, 0 to 124
Data columns (total 28 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Country Name   122 non-null    object
 1   Country Code   120 non-null    object
 2   Series Name    120 non-null    object
 3   Series Code    120 non-null    object
 4   2000 [YR2000]  120 non-null    object
 5   2001 [YR2001]  120 non-null    object
 6   2002 [YR2002]  120 non-null    object
 7   2003 [YR2003]  120 non-null    object
 8   2004 [YR2004]  120 non-null    object
 9   2005 [YR2005]  120 non-null    object
 10  2006 [YR2006]  120 non-null    object
 11  2007 [YR2007]  120 non-null    object
 12  2008 [YR2008]  120 non-null    object
 13  2009 [YR2009]  120 non-null    object
 14  2010 [YR2010]  120 non-null    object
 15  2011 [YR2011]  120 non-null    object
 16  2012 [YR2012]  120 non-null    object
 17  2013 [YR2013]  120 non-null    object
 18  2014 [YR2014]  120 non-null    object
 19  2015 [YR2015]  120 non-null    object
 20  2016 [YR2016]  120 non-null    object
 21  2017 [YR2017]  120 non-null    object
 22  2018 [YR2018]  120 non-null    object
 23  2019 [YR2019]  120 non-null    object
 24  2020 [YR2020]  120 non-null    object
 25  2021 [YR2021]  120 non-null    object
 26  2022 [YR2022]  120 non-null    object
 27  2023 [YR2023]  120 non-null    object
dtypes: object(28)
memory usage: 27.5+ KB

In [5]:
columns = df.columns
columns

Index(['Country Name', 'Country Code', 'Series Name', 'Series Code',
       '2000 [YR2000]', '2001 [YR2001]', '2002 [YR2002]', '2003 [YR2003]',
       '2004 [YR2004]', '2005 [YR2005]', '2006 [YR2006]', '2007 [YR2007]',
       '2008 [YR2008]', '2009 [YR2009]', '2010 [YR2010]', '2011 [YR2011]',
       '2012 [YR2012]', '2013 [YR2013]', '2014 [YR2014]', '2015 [YR2015]',
       '2016 [YR2016]', '2017 [YR2017]', '2018 [YR2018]', '2019 [YR2019]',
       '2020 [YR2020]', '2021 [YR2021]', '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [6]:
df.replace(to_replace = "..", value = None, inplace = True)

In [7]:
for column in columns:
    print("Column Name:", column, end="\t")
    print(df[column].isna().sum())

Column Name: Country Name	3
Column Name: Country Code	5
Column Name: Series Name	5
Column Name: Series Code	5
Column Name: 2000 [YR2000]	23
Column Name: 2001 [YR2001]	22
Column Name: 2002 [YR2002]	21
Column Name: 2003 [YR2003]	17
Column Name: 2004 [YR2004]	19
Column Name: 2005 [YR2005]	18
Column Name: 2006 [YR2006]	17
Column Name: 2007 [YR2007]	16
Column Name: 2008 [YR2008]	16
Column Name: 2009 [YR2009]	16
Column Name: 2010 [YR2010]	19
Column Name: 2011 [YR2011]	17
Column Name: 2012 [YR2012]	21
Column Name: 2013 [YR2013]	20
Column Name: 2014 [YR2014]	16
Column Name: 2015 [YR2015]	16
Column Name: 2016 [YR2016]	17
Column Name: 2017 [YR2017]	15
Column Name: 2018 [YR2018]	16
Column Name: 2019 [YR2019]	17
Column Name: 2020 [YR2020]	15
Column Name: 2021 [YR2021]	18
Column Name: 2022 [YR2022]	30
Column Name: 2023 [YR2023]	39

## Grouping by Macro Indicators

In [8]:
macro_ind_df = df.groupby(['Series Name','Country Code'])
macro_ind_df = macro_ind_df.sum()

In [9]:
macro_ind_df.replace(0, None, inplace = True)

In [10]:
macro_ind_df.head(5)

                                                       Country Name  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG           Afghanistan
                                          BGD            Bangladesh
                                          BTN                Bhutan
                                          IND                 India
                                          LKA             Sri Lanka

                                                              Series Code  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG           GC.DOD.TOTL.GD.ZS
                                          BGD           GC.DOD.TOTL.GD.ZS
                                          BTN           GC.DOD.TOTL.GD.ZS
                                          IND           GC.DOD.TOTL.GD.ZS
                                          LKA           GC.DOD.TOTL.GD.ZS

                                                           2000 [YR2000]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           37.2923933577388
                                          IND           55.0042464964554
                                          LKA           96.9040326453759

                                                           2001 [YR2001]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD           31.4618431575804
                                          BTN           67.1679909951713
                                          IND           59.0179097968845
                                          LKA           103.219274149885

                                                           2002 [YR2002]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD            31.863991518402
                                          BTN           54.1217805841119
                                          IND           62.5527712945573
                                          LKA           105.524990754701

                                                           2003 [YR2003]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD           31.2044521104432
                                          BTN           65.6287612724923
                                          IND           62.1900538960464
                                          LKA           102.270712023476

                                                           2004 [YR2004]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           71.8993384935838
                                          IND           62.5929767433885
                                          LKA           102.328536698869

                                                           2005 [YR2005]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           75.6957100342792
                                          IND           62.2265261001737
                                          LKA           90.6049131149854

                                                           2006 [YR2006]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN            71.297555656776
                                          IND           59.6667302762217
                                          LKA           88.6994841221229

                                                           2007 [YR2007]  ...  \
Series Name                               Country Code                    ...
Central government debt, total (% of GDP) AFG                       None  ...
                                          BGD                       None  ...
                                          BTN            59.811072814383  ...
                                          IND           57.4975363892468  ...
                                          LKA           84.9944169483341  ...

                                                           2014 [YR2014]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           84.9990711282336
                                          IND           49.9009248748319
                                          LKA           68.5910423335315

                                                           2015 [YR2015]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           81.0505609762618
                                          IND           49.9647183856551
                                          LKA            73.512659162998

                                                           2016 [YR2016]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           92.2912012893941
                                          IND           47.6337555915272
                                          LKA                       None

                                                           2017 [YR2017]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           95.7786849724125
                                          IND           47.5836093800197
                                          LKA                       None

                                                           2018 [YR2018]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           95.8478212264571
                                          IND           46.5224986659322
                                          LKA                       None

                                                          2019 [YR2019]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                      None
                                          BGD                      None
                                          BTN           90.357352573338
                                          IND                      None
                                          LKA                      None

                                                           2020 [YR2020]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                       None
                                          BGD                       None
                                          BTN           111.007884088239
                                          IND                       None
                                          LKA                       None

                                                       2021 [YR2021]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                   None
                                          BGD                   None
                                          BTN                   None
                                          IND                   None
                                          LKA                   None

                                                       2022 [YR2022]  \
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                   None
                                          BGD                   None
                                          BTN                   None
                                          IND                   None
                                          LKA                   None

                                                       2023 [YR2023]
Series Name                               Country Code
Central government debt, total (% of GDP) AFG                   None
                                          BGD                   None
                                          BTN                   None
                                          IND                   None
                                          LKA                   None

[5 rows x 26 columns]

In [11]:
missing_values_per_series = df.groupby(["Series Name"]).apply(lambda x:x.isna().sum().sum())
missing_values_per_series

C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\521508767.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_values_per_series = df.groupby(["Series Name"]).apply(lambda x:x.isna().sum().sum())

Series Name
Central government debt, total (% of GDP)                              108
Current health expenditure per capita (current US$)                     18
Exports of goods and services (% of GDP)                                40
Foreign direct investment, net inflows (% of GDP)                       14
GDP (current US$)                                                        1
GDP growth (annual %)                                                    2
GDP per capita (current US$)                                             1
Imports of goods and services (% of GDP)                                40
Inflation, consumer prices (annual %)                                    9
Population, female                                                       0
Population, male                                                         0
Population, total                                                        0
School enrollment, tertiary (% gross)                                   57
Tax revenue (% of GDP)                                                  51
Unemployment, total (% of total labor force) (modeled ILO estimate)      0
dtype: int64

In [12]:
total_values_per_series = df.groupby(["Series Name"]).apply(lambda x: x.size)
total_values_per_series

C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\3148958082.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  total_values_per_series = df.groupby(["Series Name"]).apply(lambda x: x.size)

Series Name
Central government debt, total (% of GDP)                              224
Current health expenditure per capita (current US$)                    224
Exports of goods and services (% of GDP)                               224
Foreign direct investment, net inflows (% of GDP)                      224
GDP (current US$)                                                      224
GDP growth (annual %)                                                  224
GDP per capita (current US$)                                           224
Imports of goods and services (% of GDP)                               224
Inflation, consumer prices (annual %)                                  224
Population, female                                                     224
Population, male                                                       224
Population, total                                                      224
School enrollment, tertiary (% gross)                                  224
Tax revenue (% of GDP)                                                 224
Unemployment, total (% of total labor force) (modeled ILO estimate)    224
dtype: int64

In [13]:
missing_values_per_cent_series = missing_values_per_series/total_values_per_series

In [14]:
print(type(missing_values_per_cent_series))
missing_values_per_cent_series

<class 'pandas.core.series.Series'>

Series Name
Central government debt, total (% of GDP)                              0.482143
Current health expenditure per capita (current US$)                    0.080357
Exports of goods and services (% of GDP)                               0.178571
Foreign direct investment, net inflows (% of GDP)                      0.062500
GDP (current US$)                                                      0.004464
GDP growth (annual %)                                                  0.008929
GDP per capita (current US$)                                           0.004464
Imports of goods and services (% of GDP)                               0.178571
Inflation, consumer prices (annual %)                                  0.040179
Population, female                                                     0.000000
Population, male                                                       0.000000
Population, total                                                      0.000000
School enrollment, tertiary (% gross)                                  0.254464
Tax revenue (% of GDP)                                                 0.227679
Unemployment, total (% of total labor force) (modeled ILO estimate)    0.000000
dtype: float64

In [15]:
missing_values_per_cent_series["Central government debt, total (% of GDP)"]

0.48214285714285715

In [16]:
type(macro_ind_df)

pandas.core.frame.DataFrame

In [17]:
type(df)

pandas.core.frame.DataFrame

## Grouping by Countries

In [18]:
country_wise_df = df.groupby(["Country Name","Series Name"])
type(country_wise_df)

pandas.core.groupby.generic.DataFrameGroupBy

In [19]:
country_wise_df = country_wise_df.sum()
country_wise_df.head(5)

                                                                Country Code  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                   AFG
             Current health expenditure per capita (current ...          AFG
             Exports of goods and services (% of GDP)                    AFG
             Foreign direct investment, net inflows (% of GDP)           AFG
             GDP (current US$)                                           AFG

                                                                          Series Code  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)              GC.DOD.TOTL.GD.ZS
             Current health expenditure per capita (current ...     SH.XPD.CHEX.PC.CD
             Exports of goods and services (% of GDP)                  NE.EXP.GNFS.ZS
             Foreign direct investment, net inflows (% of GDP)   BX.KLT.DINV.WD.GD.ZS
             GDP (current US$)                                         NY.GDP.MKTP.CD

                                                                    2000 [YR2000]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...                 0
             Exports of goods and services (% of GDP)                           0
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   3521418059.92345

                                                                    2001 [YR2001]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...                 0
             Exports of goods and services (% of GDP)                           0
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   2813571753.87253

                                                                    2002 [YR2002]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...       17.00758553
             Exports of goods and services (% of GDP)                           0
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   3825701438.99963

                                                                      2003 [YR2003]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                            0
             Current health expenditure per capita (current ...         17.81492424
             Exports of goods and services (% of GDP)                             0
             Foreign direct investment, net inflows (% of GDP)   0.0221192604146061
             GDP (current US$)                                     4520946818.54581

                                                                       2004 [YR2004]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                             0
             Current health expenditure per capita (current ...          21.42946434
             Exports of goods and services (% of GDP)                              0
             Foreign direct investment, net inflows (% of GDP)   -0.0133973940096779
             GDP (current US$)                                      5224896718.67782

                                                                      2005 [YR2005]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                            0
             Current health expenditure per capita (current ...         25.10707283
             Exports of goods and services (% of GDP)                             0
             Foreign direct investment, net inflows (% of GDP)   0.0241808474410122
             GDP (current US$)                                     6203256538.70967

                                                                    2006 [YR2006]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...       28.91982269
             Exports of goods and services (% of GDP)                           0
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   6971758282.29351

                                                                    2007 [YR2007]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...       32.71720505
             Exports of goods and services (% of GDP)                           0
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   9747886187.39393

                                                                 ...  \
Country Name Series Name                                         ...
Afghanistan  Central government debt, total (% of GDP)           ...
             Current health expenditure per capita (current ...  ...
             Exports of goods and services (% of GDP)            ...
             Foreign direct investment, net inflows (% of GDP)   ...
             GDP (current US$)                                   ...

                                                                     2014 [YR2014]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                           0
             Current health expenditure per capita (current ...        60.18957901
             Exports of goods and services (% of GDP)                            0
             Foreign direct investment, net inflows (% of GDP)   0.209664794672203
             GDP (current US$)                                    20497128555.6972

                                                                    2015 [YR2015]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...       60.05854034
             Exports of goods and services (% of GDP)                           0
             Foreign direct investment, net inflows (% of GDP)   0.88400046336123
             GDP (current US$)                                   19134221644.7325

                                                                     2016 [YR2016]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                           0
             Current health expenditure per capita (current ...        61.48645782
             Exports of goods and services (% of GDP)                            0
             Foreign direct investment, net inflows (% of GDP)   0.516606084523093
             GDP (current US$)                                    18116572395.0772

                                                                     2017 [YR2017]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                           0
             Current health expenditure per capita (current ...        66.90921783
             Exports of goods and services (% of GDP)                            0
             Foreign direct investment, net inflows (% of GDP)   0.274796791572807
             GDP (current US$)                                    18753456497.8159

                                                                     2018 [YR2018]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                           0
             Current health expenditure per capita (current ...        71.33430481
             Exports of goods and services (% of GDP)                            0
             Foreign direct investment, net inflows (% of GDP)   0.661572217787196
             GDP (current US$)                                    18053222687.4126

                                                                     2019 [YR2019]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                           0
             Current health expenditure per capita (current ...        74.23410797
             Exports of goods and services (% of GDP)                            0
             Foreign direct investment, net inflows (% of GDP)   0.124495985291258
             GDP (current US$)                                    18799444490.1128

                                                                      2020 [YR2020]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                            0
             Current health expenditure per capita (current ...         80.28805542
             Exports of goods and services (% of GDP)              10.4208171386207
             Foreign direct investment, net inflows (% of GDP)   0.0649939571808755
             GDP (current US$)                                     19955929052.1496

                                                                     2021 [YR2021]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                           0
             Current health expenditure per capita (current ...        81.31976318
             Exports of goods and services (% of GDP)              14.342152797537
             Foreign direct investment, net inflows (% of GDP)   0.215925454725649
             GDP (current US$)                                    14259995441.0759

                                                                    2022 [YR2022]  \
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...                 0
             Exports of goods and services (% of GDP)            18.3800424016375
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   14497243872.1337

                                                                    2023 [YR2023]
Country Name Series Name
Afghanistan  Central government debt, total (% of GDP)                          0
             Current health expenditure per capita (current ...                 0
             Exports of goods and services (% of GDP)            16.7751362822863
             Foreign direct investment, net inflows (% of GDP)                  0
             GDP (current US$)                                   17233051620.1117

[5 rows x 26 columns]

In [20]:
country_wise_df.columns

Index(['Country Code', 'Series Code', '2000 [YR2000]', '2001 [YR2001]',
       '2002 [YR2002]', '2003 [YR2003]', '2004 [YR2004]', '2005 [YR2005]',
       '2006 [YR2006]', '2007 [YR2007]', '2008 [YR2008]', '2009 [YR2009]',
       '2010 [YR2010]', '2011 [YR2011]', '2012 [YR2012]', '2013 [YR2013]',
       '2014 [YR2014]', '2015 [YR2015]', '2016 [YR2016]', '2017 [YR2017]',
       '2018 [YR2018]', '2019 [YR2019]', '2020 [YR2020]', '2021 [YR2021]',
       '2022 [YR2022]', '2023 [YR2023]'],
      dtype='object')

In [21]:
missing_values_per_country = df.groupby(["Country Name"]).apply(lambda x: x.isna().sum().sum())
total_values_per_country =  df.groupby(["Country Name"]).apply(lambda x: x.size)
missing_values_per_cent_country = missing_values_per_country/total_values_per_country

C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\1101962485.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_values_per_country = df.groupby(["Country Name"]).apply(lambda x: x.isna().sum().sum())
C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\1101962485.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  total_values_per_country =  df.groupby(["Country Name"]).apply(lambda x: x.size)

In [22]:
print(missing_values_per_country)

Country Name
Afghanistan                                         114
Bangladesh                                           27
Bhutan                                               28
Data from database: World Development Indicators     27
India                                                11
Last Updated: 01/28/2025                             27
Maldives                                             61
Nepal                                                16
Pakistan                                             52
Sri Lanka                                            32
dtype: int64

In [23]:
total_values_per_country

Country Name
Afghanistan                                         420
Bangladesh                                          420
Bhutan                                              420
Data from database: World Development Indicators     28
India                                               420
Last Updated: 01/28/2025                             28
Maldives                                            420
Nepal                                               420
Pakistan                                            420
Sri Lanka                                           420
dtype: int64

In [24]:
missing_values_per_cent_country

Country Name
Afghanistan                                         0.271429
Bangladesh                                          0.064286
Bhutan                                              0.066667
Data from database: World Development Indicators    0.964286
India                                               0.026190
Last Updated: 01/28/2025                            0.964286
Maldives                                            0.145238
Nepal                                               0.038095
Pakistan                                            0.123810
Sri Lanka                                           0.076190
dtype: float64

## Dropping series 

Dropping series with more than 10% of missing values and comparing how that affects the missing values from countries.

In [25]:
macro_ind_df.index[0][0]

'Central government debt, total (% of GDP)'

In [26]:
indexes = list(set(macro_ind_df.index.get_level_values("Series Name")))
print(indexes)

['Inflation, consumer prices (annual %)', 'GDP per capita (current US$)', 'Imports of goods and services (% of GDP)', 'Central government debt, total (% of GDP)', 'Tax revenue (% of GDP)', 'Unemployment, total (% of total labor force) (modeled ILO estimate)', 'School enrollment, tertiary (% gross)', 'Exports of goods and services (% of GDP)', 'GDP growth (annual %)', 'Foreign direct investment, net inflows (% of GDP)', 'GDP (current US$)', 'Population, female', 'Population, male', 'Population, total', 'Current health expenditure per capita (current US$)']

In [27]:
macro_ind_df_dropped = macro_ind_df.copy()
for index in indexes:
    if missing_values_per_cent_series[index] > 0.1:
        macro_ind_df_dropped = macro_ind_df_dropped.drop(index = index)

In [28]:
macro_ind_df_dropped.head(5)

                                                                Country Name  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG           Afghanistan
                                                   BGD            Bangladesh
                                                   BTN                Bhutan
                                                   IND                 India
                                                   LKA             Sri Lanka

                                                                       Series Code  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG           SH.XPD.CHEX.PC.CD
                                                   BGD           SH.XPD.CHEX.PC.CD
                                                   BTN           SH.XPD.CHEX.PC.CD
                                                   IND           SH.XPD.CHEX.PC.CD
                                                   LKA           SH.XPD.CHEX.PC.CD

                                                                2000 [YR2000]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG                   None
                                                   BGD              8.6186285
                                                   BTN            31.09416771
                                                   IND                     18
                                                   LKA                     44

                                                                2001 [YR2001]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG                   None
                                                   BGD             8.41617775
                                                   BTN            35.96975327
                                                   IND                     20
                                                   LKA                     41

                                                                2002 [YR2002]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            17.00758553
                                                   BGD             9.37759209
                                                   BTN            35.96072769
                                                   IND                     20
                                                   LKA                     43

                                                                2003 [YR2003]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            17.81492424
                                                   BGD             10.3110857
                                                   BTN            37.33245468
                                                   IND                     22
                                                   LKA                     42

                                                                2004 [YR2004]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            21.42946434
                                                   BGD            11.10974789
                                                   BTN            46.10057831
                                                   IND                     25
                                                   LKA                     51

                                                                2005 [YR2005]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            25.10707283
                                                   BGD            11.61940002
                                                   BTN            46.69151688
                                                   IND                     27
                                                   LKA                     57

                                                                2006 [YR2006]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            28.91982269
                                                   BGD            12.37925339
                                                   BTN            54.01427841
                                                   IND                     29
                                                   LKA                     65

                                                                2007 [YR2007]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            32.71720505
                                                   BGD            14.41430759
                                                   BTN            64.43791199
                                                   IND                     36
                                                   LKA                     73

                                                                 ...  \
Series Name                                        Country Code  ...
Current health expenditure per capita (current ... AFG           ...
                                                   BGD           ...
                                                   BTN           ...
                                                   IND           ...
                                                   LKA           ...

                                                                2014 [YR2014]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            60.18957901
                                                   BGD            30.29579544
                                                   BTN            86.81033325
                                                   IND                     57
                                                   LKA                    135

                                                                2015 [YR2015]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            60.05854034
                                                   BGD            33.53680038
                                                   BTN            96.52057648
                                                   IND                     58
                                                   LKA                    147

                                                                2016 [YR2016]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            61.48645782
                                                   BGD            39.55920792
                                                   BTN            97.18308258
                                                   IND                     60
                                                   LKA                    149

                                                                2017 [YR2017]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            66.90921783
                                                   BGD            42.27734375
                                                   BTN           103.39090729
                                                   IND                     57
                                                   LKA                    146

                                                                2018 [YR2018]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            71.33430481
                                                   BGD            44.74491119
                                                   BTN           101.69933319
                                                   IND                     58
                                                   LKA                    159

                                                                2019 [YR2019]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            74.23410797
                                                   BGD            47.66782379
                                                   BTN           115.32080841
                                                   IND                     61
                                                   LKA                    160

                                                                2020 [YR2020]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            80.28805542
                                                   BGD            50.66413116
                                                   BTN           133.70314026
                                                   IND                     64
                                                   LKA                    158

                                                                2021 [YR2021]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG            81.31976318
                                                   BGD            57.93856812
                                                   BTN           120.43117523
                                                   IND                     74
                                                   LKA                    166

                                                                2022 [YR2022]  \
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG                   None
                                                   BGD                   None
                                                   BTN                   None
                                                   IND                   None
                                                   LKA                   None

                                                                2023 [YR2023]
Series Name                                        Country Code
Current health expenditure per capita (current ... AFG                   None
                                                   BGD                   None
                                                   BTN                   None
                                                   IND                   None
                                                   LKA                   None

[5 rows x 26 columns]

In [29]:
missing_values_per_cent_series["Central government debt, total (% of GDP)"]

0.48214285714285715

In [30]:
remaining = (list(set(macro_ind_df_dropped.index.get_level_values("Series Name"))))

In [31]:
for remain in remaining:
    print(missing_values_per_cent_series[remain])

0.04017857142857143
0.004464285714285714
0.0
0.008928571428571428
0.0625
0.004464285714285714
0.0
0.0
0.0
0.08035714285714286

In [32]:
series = list(set(macro_ind_df_dropped.index.get_level_values("Series Name")))

In [33]:
macro_ind_df_dropped = macro_ind_df_dropped.reset_index()

In [34]:
compser_drop_missing_values = macro_ind_df_dropped.groupby(["Country Name"]).apply(lambda x: x.isna().sum().sum())
compser_drop_total_values = macro_ind_df_dropped.groupby(["Country Name"]).apply(lambda x: x.size)
compser_drop_missing_values_percent = compser_drop_missing_values/compser_drop_total_values

C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\2746036222.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  compser_drop_missing_values = macro_ind_df_dropped.groupby(["Country Name"]).apply(lambda x: x.isna().sum().sum())
C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\2746036222.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  compser_drop_total_values = macro_ind_df_dropped.groupby(["Country Name"]).apply(lambda x: x.size)

In [35]:
print(compser_drop_missing_values_percent)

Country Name
Afghanistan    0.075000
Bangladesh     0.007143
Bhutan         0.042857
India          0.007143
Maldives       0.007143
Nepal          0.007143
Pakistan       0.007143
Sri Lanka      0.007143
dtype: float64

In [36]:
print(missing_values_per_cent_country)

Country Name
Afghanistan                                         0.271429
Bangladesh                                          0.064286
Bhutan                                              0.066667
Data from database: World Development Indicators    0.964286
India                                               0.026190
Last Updated: 01/28/2025                            0.964286
Maldives                                            0.145238
Nepal                                               0.038095
Pakistan                                            0.123810
Sri Lanka                                           0.076190
dtype: float64

In [37]:
print(compser_drop_missing_values["Afghanistan"])
print(compser_drop_total_values["Afghanistan"])

21
280

In [38]:
missing_values_per_series_country = macro_ind_df_dropped.groupby(["Series Name", "Country Name"]).apply(lambda x: x.isna().sum().sum())
total_values_per_series_country = macro_ind_df_dropped.groupby(["Series Name", "Country Name"]).apply(lambda x: x.size)
series_country_missing_percent = missing_values_per_series_country/total_values_per_series_country

C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\1705666606.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_values_per_series_country = macro_ind_df_dropped.groupby(["Series Name", "Country Name"]).apply(lambda x: x.isna().sum().sum())
C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\1705666606.py:2: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  total_values_per_series_country = macro_ind_df_dropped.groupby(["Series Name", "Country Name"]).apply(lambda x: x.size)

In [44]:
count = 1
for index in series:
    print("Missing values for:", index, "\t index ", count)
    print(missing_values_per_series_country[index])
    print(series_country_missing_percent[index])
    count += 1

Missing values for: Inflation, consumer prices (annual %) 	 index  1
Country Name
Afghanistan    9
Bangladesh     0
Bhutan         0
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.321429
Bangladesh     0.000000
Bhutan         0.000000
India          0.000000
Maldives       0.000000
Nepal          0.000000
Pakistan       0.000000
Sri Lanka      0.000000
dtype: float64
Missing values for: GDP per capita (current US$) 	 index  2
Country Name
Afghanistan    0
Bangladesh     0
Bhutan         1
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.000000
Bangladesh     0.000000
Bhutan         0.035714
India          0.000000
Maldives       0.000000
Nepal          0.000000
Pakistan       0.000000
Sri Lanka      0.000000
dtype: float64
Missing values for: Unemployment, total (% of total labor force) (modeled ILO estimate) 	 index  3
Country Name
Afghanistan    0
Bangladesh     0
Bhutan         0
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.0
Bangladesh     0.0
Bhutan         0.0
India          0.0
Maldives       0.0
Nepal          0.0
Pakistan       0.0
Sri Lanka      0.0
dtype: float64
Missing values for: GDP growth (annual %) 	 index  4
Country Name
Afghanistan    1
Bangladesh     0
Bhutan         1
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.035714
Bangladesh     0.000000
Bhutan         0.035714
India          0.000000
Maldives       0.000000
Nepal          0.000000
Pakistan       0.000000
Sri Lanka      0.000000
dtype: float64
Missing values for: Foreign direct investment, net inflows (% of GDP) 	 index  5
Country Name
Afghanistan    7
Bangladesh     0
Bhutan         7
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.25
Bangladesh     0.00
Bhutan         0.25
India          0.00
Maldives       0.00
Nepal          0.00
Pakistan       0.00
Sri Lanka      0.00
dtype: float64
Missing values for: GDP (current US$) 	 index  6
Country Name
Afghanistan    0
Bangladesh     0
Bhutan         1
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.000000
Bangladesh     0.000000
Bhutan         0.035714
India          0.000000
Maldives       0.000000
Nepal          0.000000
Pakistan       0.000000
Sri Lanka      0.000000
dtype: float64
Missing values for: Population, female 	 index  7
Country Name
Afghanistan    0
Bangladesh     0
Bhutan         0
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.0
Bangladesh     0.0
Bhutan         0.0
India          0.0
Maldives       0.0
Nepal          0.0
Pakistan       0.0
Sri Lanka      0.0
dtype: float64
Missing values for: Population, male 	 index  8
Country Name
Afghanistan    0
Bangladesh     0
Bhutan         0
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.0
Bangladesh     0.0
Bhutan         0.0
India          0.0
Maldives       0.0
Nepal          0.0
Pakistan       0.0
Sri Lanka      0.0
dtype: float64
Missing values for: Population, total 	 index  9
Country Name
Afghanistan    0
Bangladesh     0
Bhutan         0
India          0
Maldives       0
Nepal          0
Pakistan       0
Sri Lanka      0
dtype: int64
Country Name
Afghanistan    0.0
Bangladesh     0.0
Bhutan         0.0
India          0.0
Maldives       0.0
Nepal          0.0
Pakistan       0.0
Sri Lanka      0.0
dtype: float64
Missing values for: Current health expenditure per capita (current US$) 	 index  10
Country Name
Afghanistan    4
Bangladesh     2
Bhutan         2
India          2
Maldives       2
Nepal          2
Pakistan       2
Sri Lanka      2
dtype: int64
Country Name
Afghanistan    0.142857
Bangladesh     0.071429
Bhutan         0.071429
India          0.071429
Maldives       0.071429
Nepal          0.071429
Pakistan       0.071429
Sri Lanka      0.071429
dtype: float64

In [45]:
df = macro_ind_df_dropped

## Checking Missing Values per year

In [53]:
missing_values_per_year = df.groupby([ "Series Name","Country Name"]).apply(lambda x: x.isna().sum())
print(missing_values_per_year.sum())

Series Name       0
Country Code      0
Country Name      0
Series Code       0
2000 [YR2000]     5
2001 [YR2001]     4
2002 [YR2002]     3
2003 [YR2003]     2
2004 [YR2004]     2
2005 [YR2005]     1
2006 [YR2006]     1
2007 [YR2007]     1
2008 [YR2008]     0
2009 [YR2009]     0
2010 [YR2010]     0
2011 [YR2011]     0
2012 [YR2012]     0
2013 [YR2013]     0
2014 [YR2014]     0
2015 [YR2015]     0
2016 [YR2016]     0
2017 [YR2017]     0
2018 [YR2018]     0
2019 [YR2019]     0
2020 [YR2020]     1
2021 [YR2021]     1
2022 [YR2022]    10
2023 [YR2023]    14
dtype: int64

C:\Users\Sulav\AppData\Local\Temp\ipykernel_21520\2433300022.py:1: DeprecationWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  missing_values_per_year = df.groupby([ "Series Name","Country Name"]).apply(lambda x: x.isna().sum())